spring:
    datasource:
        url: jdbc:mysql://localhost:3306/security_demo
        username: root
        password: root
    jpa:
        generate-ddl: true
        properties:
            hibernate:
                ddl-auto: update
                dialect: org.hibernate.dialect.MySQL5Dialect

jwt:
    secret:
        key: someSecretKeyForToken
    valid:
        time: 300000
