spring:
    datasource:
        username: root
        password: 5202
        url: jdbc:mysql://localhost:3306/security_demo
    jpa:
        show-sql: false
        open-in-view: false
        generate-ddl: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect


    mail:
        host: smtp.google.com
        port: 587
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
        username: tomeyan.artur@gmail.com
        password:

jwt:
    secret:
        key: someSecretKeyForToken
    valid:
        time: 300000
